version: "3.5"

services:
  web_server:
    build: .
    image: gomaxPosition
    container_name: gomaxPositionCon
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    volumes:
      - .:/gomaxPosition/
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgresdb
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    ports:
      - "5435:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123456
    ports:
      - "2050:80"
    volumes:
      - ./db_admin/pg_admin_server.json:/pgadmin4/servers.json
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web_server

volumes:
  postgres:
