"""initial

Revision ID: cb7c01960bfd
Revises: 
Create Date: 2024-01-28 12:25:04.145734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7c01960bfd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_data', 'device_imei')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_data', sa.Column('device_imei', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
