"""init

Revision ID: f6a0308d2590
Revises: 
Create Date: 2024-01-19 03:46:04.768218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a0308d2590'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('angle', sa.Integer(), nullable=True))
    op.add_column('location', sa.Column('params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'params')
    op.drop_column('location', 'angle')
    # ### end Alembic commands ###
